name: Test code and app
on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - params.yaml
      
jobs:
  test_model:
    name: Test processed code and model
    runs-on: windows-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v4
        
      - name: Git config email  
        run: git config --global user.email "rashmikaslikar@outlook.de"

      - name: Git config name  
        run: git config --global user.name "Rashmi Kaslikar"

      - name: Environment setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        #$CONDA/bin/conda env update --file environment.yml --name base

      #- name: dvc version
      #  run:  dvc doctor
        
      - name: Pull data and model
        #env:
          #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: dvc pull -r myremote -v

      - name: Run tests
        run: pytest

      #- name: Evaluate model
      #  run: dvc exp run evaluate

      - name: Iterative CML setup
        uses: iterative/setup-cml@v1
    
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add the metrics to the report
          dvc metrics show --show-md >> report.md
          # Add the parameters to the report
          cat dvclive/params.yaml >> report.md
          # Create a report in PR
          cml comment create report.md 